version: "3"
services:
  portfolio_api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: portfolio_api
  portfolio_client:
    build: ./client
    ports:
      - "3000:80"
    container_name: portfolio_client
  db:
    image: mongo
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - ./api/mongo/data:/data/db
volumes:
  db: