version: "3"
services:
  api:
    build: ./api
    ports:
      - "8002:8080"
    depends_on:
      - db
    container_name: api
  client:
    build: ./client
    ports:
      - "3002:80"
    container_name: client
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: db