version: "3"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: api
  client:
    build: ./client
    ports:
      - "3000:80"
    container_name: client
    volumes:
      - /client:/usr/src/app
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - /api/mongo/data:/usr/src/app